#!/usr/bin/env bash
# deploy/nocodb-edition/setup.sh
#
# First-time bootstrap for the Postgres + NocoDB edition on an
# Oracle Cloud (or any Ubuntu) VM.
#
# What this script does (idempotent — safe to re-run):
#
#   1. Installs Docker Engine + the Compose plugin if missing.
#   2. Installs Python 3.10+ + venv for the chat bot.
#   3. Creates ./.venv and installs the bot in editable mode with
#      [telegram, nocodb] extras.
#   4. Generates deploy/nocodb-edition/.env-deploy with strong random
#      POSTGRES_PASSWORD and NC_AUTH_JWT_SECRET.
#   5. Starts the postgres + nocodb containers.
#   6. Waits for Postgres to come healthy, then runs Alembic
#      migrations to create the transactions / audit_log schema.
#   7. Symlinks the systemd unit into /etc/systemd/system/.
#
# After this script finishes, you still need to:
#
#   * Edit ~/expense-tracker-bot/.env with TELEGRAM_BOT_TOKEN,
#     LLM keys, and DATABASE_URL pointing at the local Postgres.
#   * Run: sudo systemctl enable --now expense-bot
#   * Browse to http://<vm-public-ip>:8080 and create your NocoDB
#     admin user; then add a "Postgres" connection pointing at the
#     same `transactions` table.
#
# See DEPLOY.md for the full runbook with screenshots + explanations.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DEPLOY_DIR="${REPO_ROOT}/deploy/nocodb-edition"
ENV_FILE="${DEPLOY_DIR}/.env-deploy"
COMPOSE_FILE="${DEPLOY_DIR}/docker-compose.yml"
SERVICE_SRC="${DEPLOY_DIR}/expense-bot.service"
SERVICE_DST="/etc/systemd/system/expense-bot.service"

echo "==> nocodb edition setup starting"
echo "    REPO_ROOT=${REPO_ROOT}"
cd "${REPO_ROOT}"

# ─── 1. System packages ────────────────────────────────────────────────

echo
echo "==> 1/7  Installing system packages (Docker, Python, build tools)..."
sudo apt-get update -qq
sudo apt-get install -y --no-install-recommends \
    python3 python3-venv python3-pip \
    ca-certificates curl gnupg git tzdata

# Docker Engine + Compose plugin (idempotent — official install script).
if ! command -v docker >/dev/null 2>&1; then
    echo "    Installing Docker Engine ..."
    curl -fsSL https://get.docker.com | sudo sh
    sudo usermod -aG docker "${USER}" || true
    echo "    NOTE: log out + back in for the docker group to apply."
fi

# ─── 2. Python venv + project install ──────────────────────────────────

echo
echo "==> 2/7  Creating Python venv + installing bot ..."
if [ ! -d "${REPO_ROOT}/.venv" ]; then
    python3 -m venv "${REPO_ROOT}/.venv"
fi
# shellcheck disable=SC1091
source "${REPO_ROOT}/.venv/bin/activate"
pip install --upgrade pip
pip install -e ".[telegram,nocodb]"

# ─── 3. Generate .env-deploy with strong random secrets ────────────────

echo
echo "==> 3/7  Generating .env-deploy (random secrets) ..."
if [ ! -f "${ENV_FILE}" ]; then
    POSTGRES_PASSWORD="$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)"
    NC_AUTH_JWT_SECRET="$(openssl rand -base64 32 | tr -d '/+=' | head -c 48)"
    PUBLIC_URL="http://$(curl -fsS https://api.ipify.org 2>/dev/null || echo "localhost"):8080"
    cat > "${ENV_FILE}" <<EOF
# Auto-generated by setup.sh.  DO NOT commit to git.
POSTGRES_USER=expense
POSTGRES_DB=expense
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
NC_AUTH_JWT_SECRET=${NC_AUTH_JWT_SECRET}
NC_PUBLIC_URL=${PUBLIC_URL}
EOF
    chmod 600 "${ENV_FILE}"
    echo "    Wrote ${ENV_FILE}"
else
    echo "    ${ENV_FILE} already exists — skipping (delete it to regenerate)."
fi

# ─── 4. Start containers ────────────────────────────────────────────────

echo
echo "==> 4/7  Starting postgres + nocodb containers ..."
sudo docker compose --env-file "${ENV_FILE}" -f "${COMPOSE_FILE}" up -d

echo
echo "==> 5/7  Waiting for Postgres to come healthy ..."
for i in {1..30}; do
    if sudo docker compose --env-file "${ENV_FILE}" -f "${COMPOSE_FILE}" \
            exec -T postgres pg_isready -q; then
        echo "    Postgres is healthy."
        break
    fi
    sleep 2
done

# ─── 5. Apply schema via Alembic ────────────────────────────────────────

echo
echo "==> 6/7  Applying Alembic migrations ..."
# shellcheck disable=SC1091
source "${ENV_FILE}"
export DATABASE_URL="postgresql+psycopg://${POSTGRES_USER:-expense}:${POSTGRES_PASSWORD}@127.0.0.1:5432/${POSTGRES_DB:-expense}"
export STORAGE_BACKEND=nocodb
"${REPO_ROOT}/.venv/bin/alembic" -c "${REPO_ROOT}/alembic.ini" upgrade head

# ─── 6. systemd unit ────────────────────────────────────────────────────

echo
echo "==> 7/7  Installing systemd unit ..."
if [ -L "${SERVICE_DST}" ] || [ -f "${SERVICE_DST}" ]; then
    echo "    ${SERVICE_DST} already present — leaving as-is."
else
    sudo ln -s "${SERVICE_SRC}" "${SERVICE_DST}"
    sudo systemctl daemon-reload
    echo "    Linked ${SERVICE_DST} -> ${SERVICE_SRC}"
fi

cat <<'NEXT'

============================================================
nocodb edition setup complete.

Next steps:

  1. Edit your .env (~/expense-tracker-bot/.env) so it has at
     minimum:

         STORAGE_BACKEND=nocodb
         DATABASE_URL=<the URL printed above>
         TELEGRAM_BOT_TOKEN=...
         TELEGRAM_ALLOWED_USERS=...
         GROQ_API_KEY=...           # or your LLM provider of choice

     The DATABASE_URL is also stored in
     deploy/nocodb-edition/.env-deploy (mode 600) for reference.

  2. Start the bot:

         sudo systemctl enable --now expense-bot
         sudo journalctl -u expense-bot -f

  3. Open NocoDB in your browser:

         http://<vm-public-ip>:8080

     Create the admin user, then add a Postgres connection
     using the credentials in .env-deploy.  The `transactions`
     and `transactions_audit_log` tables are already there
     (created by the migration above).

See DEPLOY.md for the full runbook.
============================================================
NEXT
